## Introducción
En este ejercicio vas a crear tu propio juego de **Hundir la flota** en Python. Para el desarrollo del programa necesitarás conocimientos de la librería `numpy`, módulos, bucles, funciones y colecciones de Python. Se recomienda desarrollar el programa en un IDE como Pycharm, Visual Studio Code o Spyder. **Por lo que la entrega deberá constar de uno o varios scripts de Python (archivos .py), los que necesite el alumno**.

## ¿Cómo funciona el juego?
Vamos a realizar una versión que tiene algunas particularidades respecto al juego original, de manera que sea más sencillo el desarrollo. Veamos cómo funciona:

1. Hay dos jugadores: tu y la maquina
2. Un **tablero de 10 x 10** posiciones donde irán los barcos.
3. Lo primero que se hace es colocar los barcos. Para este juego **los barcos se colocan de manera aleatoria. Ahora bien, puedes empezar colocando los barcos en unas posiciones fijas, que no cambien con cada partida, y después implementarlo aleatoriamente, ya que es más complejo. Los barcos son:**
    * 4 barcos de 1 posición de eslora
    * 3 barcos de 2 posiciones de eslora
    * 2 barcos de 3 posiciones de eslora
    * 1 barco de 4 posiciones de eslora

4. Tanto tu, como la maquina tenéis un tablero con barcos, y se trata de ir "disparando" y hundiendo los del adversario hasta que un jugador se queda sin barcos, y por tanto, pierde.
5. Funciona por turnos y empiezas tu.
6. En cada turno disparas a una coordenada (X, Y) del tablero adversario. **Si aciertas, te vuelve a tocar**. En caso contrario, le toca a la maquina.
7. En los turnos de la maquina, si acierta, también le vuelve a tocar. ¿Dónde dispara la maquina? A un punto aleatorio en tu tablero.
8. Si se hunden todos los barcos de un jugador, el juego acaba y gana el otro.
9. Por norma del juego no puede haber espacios entre barcos. Ignora esta norma

En [esta página](http://es.battleship-game.org/) podrás probarlo online.
## Desarrollo
Tendrás que desarrollar lo siguiente:
1. Necesitarás un conjunto de **constantes**, donde tengas inventariados los barcos del juego, dimensiones y demás variables que no vayan a cambiar.

2. Varias funciones que realicen lo siguiente:
    * Una función que inicialice el tablero de cada jugador, donde se creen los tableros de 10x10 y se posicionen los barcos. Mucho cuidado si los posicionas aleatoriamente, de no superponer unos sobre otros, de no salirte del tablero y que que los barcos no estén en diagonal.
    * Piensa que tendrás que manejar 4 arrays de numpy para los tableros. Cada jugador tendrá un array de numpy con sus barcos y los impactos del otro jugador, y además otro array de numpy solo con los impactos, ya que ese es el tablero que utiliza el otro jugador para realizar sus disparos. Cuando vayas a jugar tendrás que ver tu tablero con tus barcos y el del otro jugador con los impactos que has hecho.
    * Necesitas una función de **buscar coordenada**. Cuando hay un disparo de un jugador en ese tablero, tendrás que comprobar si ahi había un barco, o simplemente agua. Acuérdate de marcar en el tablero, tanto si hay un impacto, como si dio agua.


3. Una vez ya tienes montado tu tablero, hay que montar el programa:
    * El programa no es más que el **típico `while true: `, con una serie de inputs del usuario**. Se está ejecutando constantemente y le pide al usuario coordenadas para comprobar si impacta.
    * Cuando arranque el programa, primero pon algún mensaje de bienvenida y las instrucciones del juego.
    * A continuación **inicializa los tableros de ambos jugadores** con los barcos. Estas dos primeras acciones solo se ejecutan una vez!! Que es el comienzo del juego.
    * Después de eso ya comienza el juego. Básicamente **se irá ejecutando iterativamente en el `while`, y le irá preguntando coordenadas al usuario.**
    * Recoges coordenadas, compruebas en el tablero de la maquina si habia barco.
        * Hay barco: marca en el tablero de la maquina el impacto y le vuelve a tocar al usuario
        * No hay barco: le toca a la maquina. O lo que es lo mismo, escoge una coordenada aleatoria, y comprueba en el tablero del usuario si habia barco.
    * **Así hasta que uno de los dos jugadores se quede sin barcos, y termina el juego.**
    * Cuando empiece tu turno deberías imprimir por pantalla tu tablero, para ver cuántos impactos te ha hecho la máquina, así como el tablero con los impactos que has hecho tu en el adversario, de manera que te sirva de ayuda para el siguiente disparo.

Hay infinidad de maneras para resolver este ejercicio, por lo que siéntete libre de implementarlo de la forma que te resulte más cómoda.

1. Tablero:
   * Vale con el tablero de numpy II? yo creo que si
   * En uno hay que marcar los barcos y cómo te hunden y en otro el del contrincante. Realmente son casi iguales 2 a 2. pero en uno se verían los barcos y donde han disparado y en el otro dónde han disparado y si hay barco o no.
        
2. Barcos:
   * Un objeto que llame a una función? El argumento de entrada sería su eslora
   * 4 barcos de 1 cuadro
   * 3 barcos de 2 cuadros
   * 2 barcos de 3 cuadros
   * 1 barco de 4 cuadros
   * Los barcos no pueden ni salirse del tablero ni apilarse. 
   * Hay que catarse del numero de vidas de cada barco? o del total (20)
3. Disparo:
   * Funcion del numpy II.
   * El ordena dispara aleatoriamente? supongo
   * La maquina se tiene que acordar de dónde ha disparado para no repetirlo. Se pueden ir metiendo los disparos en una lista para que no se repita. El alvaro lo ha hecho con in if y un elese que igual es mejor
   * Si se acierta vuelve a tirar. Con un while ahsta que pierda??
   * Una función con un input dentro i guess
* Al inicio del juego solo se ponen los barcos una vez!!!



In [23]:
import numpy as np
import random
#TABLERO
tab = np.arange(1, 101).reshape(10,10)
tab = np.where(tab, " ", tab)
#Habría que hacer 4 de estos, dos apra ti y dos para la maquína. 
#Barcos. Pa mi que esto no esta bien. los barcos verticales van demasiado sketchy. demasiado if
#Para colocar los barcos
def barcos():
    esloras = [1,1,1,1,2,2,2,3,3,4]
    for eslora in esloras:
        x = random.randint(1,2)
        if x== 1:
            print(barco_vertical(eslora))
        if x == 2:
            print(barco_horizontal(eslora))
#Pra los barcos horizontales
def barco_horizontal(eslora):
    while True:
        x = random.randint(1,10)
        if x<=11-eslora:
             break
    barco_h= np.arange(x, x+eslora)
    return (barco_h)
#PAra los barcos verticales
def barco_vertical(eslora):
    while True:

        x = random.randint(1,10)
        if x<=11-eslora:
             break
    barco_v = np.arange(x,x+eslora).reshape(eslora,1)
    return barco_v


In [24]:
tab = np.arange(1, 101).reshape(10,10)
tab = np.where(tab, " ", tab)
#Esto es para emter los horizontales en el tablero. PEro habria que mirarlo más
def barcos_col():
    esloras = [1,1,1,1,2,2,2,3,3,4]
    for eslora in esloras:
        z = 1
        if z== 1:
            print(barco_horizontal(eslora))
def barco_horizontal(eslora):
    while True:
        x = random.randint(1,10)
        if x<11-eslora:
             break
    barco_h= np.arange(x, x+eslora)
    y = random.randint(1,10)
    tab[y][x:x+eslora]='O'
    return barco_h
barcos_col()
tab

[1]
[9]
[8]
[8]
[6 7]


IndexError: index 10 is out of bounds for axis 0 with size 10

In [30]:
tab = np.arange(1, 101).reshape(10,10)
tab = np.where(tab, " ", tab)
def colocabarcos_v(x, eslora):
    y =random.randint(0,9)
    if eslora == 4:
        tab[[x],[y]]='O'
        tab[[x+1],[y]]='O'
        tab[[x+2],[y]]='O'
        tab[[x+3],[y]]='O'
    elif eslora ==3:
        tab[[x],[y]]='O'
        tab[[x+1],[y]]='O'
        tab[[x+2],[y]]='O'
    elif eslora ==2:
        tab[[x],[y]]='O'
        tab[[x+1],[y]]='O'
    elif eslora==1:
        tab[[x],[y]]='O'
def colocabarcos_h(x,eslora):
    y = random.randint(0,9)
    tab[y][x:x+eslora]='O'
def barcos():
    esloras = [1,1,1,1,2,2,2,3,3,4]
    for eslora in esloras:
        x = random.randint(1,2)
        if x== 1:
            print(barco_vertical(eslora))
        if x == 2:
            print(barco_horizontal(eslora))
def barco_horizontal(eslora):
    while True:
        x = random.randint(1,10)
        if x<=11-eslora:
             break
    barco_h= np.arange(x, x+eslora)
    colocabarcos_h(x,eslora)
    return (barco_h)
def barco_vertical(eslora):
    while True:

        x = random.randint(1,10)
        if x<=11-eslora:
             break
    barco_v = np.arange(x,x+eslora).reshape(eslora,1)
    colocabarcos_v(x,eslora)
    return barco_v
barcos()
tab

[10]
[3]
[[5]]
[[7]]
[[3]
 [4]]
[[7]
 [8]]
[[7]
 [8]]
[2 3 4]
[6 7 8]
[4 5 6 7]


array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', 'O', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', 'O', 'O', 'O', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', 'O', ' ', ' ', ' '],
       [' ', ' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', 'O', 'O', 'O', 'O', 'O', ' ', ' '],
       [' ', 'O', 'O', ' ', ' ', ' ', ' ', ' ', ' ', 'O'],
       [' ', 'O', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U11')

In [21]:
tab = np.arange(1, 101).reshape(10,10)
tab = np.where(tab, " ", tab)
#Esto es para meter los barcos verticales en el tablero. Habría que meterlo todo en barcos(), aplicarlo a lo del 1/2 y hacer para que no se pisen
def barcos():
    esloras = [1,1,1,1,2,2,2,3,3,4]
    for eslora in esloras:
        x = 1 #random.randint(1,2)
        if x== 1:
            print(barco_vertical(eslora))
        if x == 2:
            print(barco_horizontal(eslora))
def barco_vertical(eslora):
    while True:
        x = random.randint(0,9)
        if x<=11-eslora:
             break
    barco_v = np.arange(x,x+eslora).reshape(eslora,1)
    y =random.randint(0,9)
    if eslora == 4:
        tab[[x],[y]]='O'
        tab[[x+1],[y]]='O'
        tab[[x+2],[y]]='O'
        tab[[x+3],[y]]='O'
    elif eslora ==3:
        tab[[x],[y]]='O'
        tab[[x+1],[y]]='O'
        tab[[x+2],[y]]='O'
    elif eslora ==2:
        tab[[x],[y]]='O'
        tab[[x+1],[y]]='O'
    elif eslora==1:
        tab[[x],[y]]='O'
    return
barcos()
tab

    

None
None
None
None
None
None
None
None
None
None


array([[' ', 'O', ' ', ' ', ' ', ' ', 'O', ' ', ' ', 'O'],
       [' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'O'],
       ['O', 'O', 'O', ' ', ' ', ' ', 'O', ' ', ' ', ' '],
       ['O', 'O', 'O', ' ', ' ', ' ', 'O', 'O', ' ', ' '],
       [' ', ' ', 'O', ' ', ' ', ' ', 'O', 'O', ' ', ' '],
       [' ', ' ', ' ', ' ', 'O', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'O'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'O'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U11')